version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/prototype
    depends_on:
      - php
      - mysql
  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/var/www/prototype
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    env_file:
      - "docker/mysql.env"
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./app:/var/www/prototype
